/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


/******************************************************************************/
/*                              INCLUDE FILES                                 */
/******************************************************************************/

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <system_stm32f4xx.h>
#include <timer.h>
#include <eventman.h>
#include <led.h>
#include <melody.h>
#include <lightsensor.h>
#include <temhumsensor.h>
#include <button.h>
#include <Ucglib.h>
#include <eventbutton.h>

/******************************************************************************/
/*                     PRIVATE TYPES and DEFINITIONS                         */
/******************************************************************************/
// dinh nghia kieu du lieu enum cho cac su kien va trang thai cua ctr chinh

typedef enum {
	EVENT_EMPTY,
	EVENT_APP_INIT,
	EVENT_APP_FLUSHMEM_READY,

} event_api_t, *event_api_p;

typedef enum {
	STATE_APP_STARTUP,
	STATE_APP_IDLE,
	STATE_APP_RESET
} state_app_t;

/******************************************************************************/
/*                     EXPORTED TYPES and DEFINITIONS                         */
/******************************************************************************/


/******************************************************************************/
/*                              PRIVATE DATA                                  */
/******************************************************************************/
//khai bao ham nguyen mau
static ucg_t ucg;
uint8_t eCurrentState;
static uint8_t IdTimer = NO_TIMER;
static uint8_t levelLed = 0;
void LedUp(void *data);
void LedDown(void *data);
float temperature, humidity, light_intensity;
static uint8_t idTimerSensorScan = NO_TIMER;

static char src1[20] = "";
static char src2[20] = "";
static char src3[20] = "";



void LedUp(void *data)
{
	if(levelLed < 100)
	{
		LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_GREEN, levelLed);
		levelLed ++;
	}
}
void LedDown(void *data)
{
	if(levelLed > 0)
	{
		LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_GREEN, levelLed);
		levelLed --;
	}
}


static uint8_t count = 0;
static uint8_t brightness = 0;
void blinkLed(void *data) { //hàm nháy led sau 5 lần nhấn B3 trên board
    if (count < 10) { //cứ 2 giá trị của count là 1 lần bật&tắt
        if (brightness == 0) {
            brightness = 50;
        } else {
            brightness = 0;
        }

        // Bật/tắt LED với độ sáng mới
        LedControl_SetAllColor(LED_COLOR_GREEN, brightness);
        count++;
    }
}

//Xây dựng hàm Task_multiSensorScan để lấy thông tin nhiệt độ, độ ẩm và hiển thị lên LCD.
void Task_multiSensorScan(void) {

	uint8_t state = 0;
    // Đọc giá trị nhiệt độ và độ ẩm từ cảm biến nhiệt độ và độ ẩm
    temperature = TemHumSensor_GetTemp();
    humidity = TemHumSensor_GetHumi();

    // Đọc giá trị cường độ ánh sáng từ cảm biến ánh sáng ở chế độ DMA
    light_intensity = LightSensor_MeasureUseDMAMode();

    if (state == 0){
	ucg_ClearScreen(&ucg);
	state = 1;
    }
	memset(src1, 0, sizeof(src1));
	sprintf(src1, "Temp = %f oC ", temperature);
	ucg_DrawString(&ucg, 0, 32, 0,src1);

    memset(src2, 0, sizeof(src2));
	sprintf(src2, "Hum = %f %% ", humidity);
	ucg_DrawString(&ucg, 0, 32, 0,src2);

	memset(src3, 0, sizeof(src3));
	sprintf(src3, "Lux = %f lux ", light_intensity);
	ucg_DrawString(&ucg, 0, 32, 0,src3);



}



static void SetStateApp(
		state_app_t state
){
	eCurrentState = state;
}

static state_app_t
GetStateApp(void){
	return eCurrentState;
}

static void LoadConfiguration(void){
	// in dong chu ra LCD
			ucg_DrawString(&ucg, 0, 12, 0, "IOT Programming"); // vi tri hang ngang la 0, hang doc la 12, chieu hien thi 0 nam ngang man hinh
			ucg_DrawString(&ucg, 0, 26, 0, "by Lumi Smarthome");
}

void
DeviceStateMachine(
		uint8_t event
){
	switch (event){
		case EVENT_OF_BUTTON_0_PRESS_5_TIMES:
		{
			if(IdTimer != NO_TIMER)
						{
							TimerStop(IdTimer);
							IdTimer = NO_TIMER;
						}
						count = 0;
						IdTimer = TimerStart("BlinkTimer", 500, 10,(void*) blinkLed, NULL);

			ucg_ClearScreen(&ucg);
			ucg_DrawString(&ucg, 0, 12, 0, "DEVICE: Board STM32");
			ucg_DrawString(&ucg, 0, 24, 0, "Nucleo");
			ucg_DrawString(&ucg, 0, 36, 0, "CODE: ");
			ucg_DrawString(&ucg, 0, 48, 0, "STM32F401RE_NUCLEO");
			ucg_DrawString(&ucg, 0, 60, 0, "MANUFACTURER: ");
			ucg_DrawString(&ucg, 0, 72, 0, "STMicroelectronics");
			ucg_DrawString(&ucg, 0, 84, 0, "KIT EXPANSION: ");
			ucg_DrawString(&ucg, 0, 96, 0, "Lumi Smarthome");
			ucg_DrawString(&ucg, 0, 108, 0, "PROJECT: ");
			ucg_DrawString(&ucg, 0, 120, 0, "Simulator touch switch");
		}	break;


		if (idTimerSensorScan != NO_TIMER)
		{
			TimerStop(idTimerSensorScan);
		}
		idTimerSensorScan = TimerStart("Task_multiSensorScan", 5000, TIMER_REPEAT_FOREVER, (void*)Task_multiSensorScan, NULL );
		static uint8_t button1count = 0;
		case EVENT_OF_BUTTON_1_PRESS_LOGIC:
		{
			if (button1count == 0){
			LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_RED, 50);
			BuzzerControl_SetMelody(pbeep);
			button1count = 1;
			} else {
				LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_RED, 0);
				BuzzerControl_SetMelody(pbeep);
				button1count = 0;
			}
		}	break;

		static uint8_t button2count = 0;
		case EVENT_OF_BUTTON_2_PRESS_LOGIC:
		{

			if (button2count == 0){
			LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_GREEN, 50);
			BuzzerControl_SetMelody(pbeep);
			button2count = 1;
			} else {
				LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_GREEN, 0);
				BuzzerControl_SetMelody(pbeep);
				button2count = 0;
			}
		}	break;

		static uint8_t button3count = 0;
		case EVENT_OF_BUTTON_3_PRESS_LOGIC:
		{

			if (button3count == 0){
			LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_BLUE, 50);
			BuzzerControl_SetMelody(pbeep);
			button3count = 1;
			} else {
				LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_BLUE, 0);
				BuzzerControl_SetMelody(pbeep);
				button3count = 0;
			}
		}	break;

		static uint8_t button4count = 0;
		case EVENT_OF_BUTTON_4_PRESS_LOGIC:
		{

			if (button4count == 0){
			LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_WHITE, 50);
			BuzzerControl_SetMelody(pbeep);
			button4count = 1;
			} else {
				LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_WHITE, 0);
				BuzzerControl_SetMelody(pbeep);
				button4count = 0;
			}
		}	break;

		case EVENT_OF_BUTTON_1_HOLD_1S:
		{
			if(IdTimer != NO_TIMER)
						{
							TimerStop(IdTimer);
							IdTimer = NO_TIMER;
						}

						IdTimer = TimerStart("LedDown", 50, TIMER_REPEAT_FOREVER, (void*)LedDown, NULL);
		} break;

		case EVENT_OF_BUTTON_1_RELEASED_1S:
		{
			if(IdTimer != NO_TIMER)
					{
						TimerStop(IdTimer);
						IdTimer = NO_TIMER;
		} break;
		default:
			break;
	}

	}
}




/*
//Xây dựng hàm MultiSensorScan để cập nhật nhiệt độ, độ ẩm một giây một lần

uint32_t last_scan_time = 0;  // Thời điểm lần cuối cùng quét cảm biến

void MultiSensorScan() {
    uint32_t current_time = GetMilSecTick();  // Lấy thời gian thực từ timer system tick

    // Kiểm tra xem đã đủ một giây kể từ lần cuối cùng quét cảm biến chưa
    if (current_time - last_scan_time >= 1000) {


        // Đọc giá trị nhiệt độ và độ ẩm từ cảm biến nhiệt độ và độ ẩm
        temperature = TemHumSensor_GetTemp();
        humidity = TemHumSensor_GetHumi();
        // Cập nhật thời gian lần cuối cùng quét cảm biến
        last_scan_time = current_time;
    }
}
*/
// Khai báo hàm AppStateManager để xử lý các sự kiện của chương trình chính như sau
static void
AppStateManager(
		uint8_t event
	){
	switch (GetStateApp()){
		case STATE_APP_STARTUP:
			if (event == EVENT_APP_INIT )
			{
				LoadConfiguration();
				SetStateApp(STATE_APP_IDLE);
			}
			break;

		case STATE_APP_IDLE:
			DeviceStateMachine(event);
			break;

		case STATE_APP_RESET:
			break;

		default:
			break;
	}

}

// xay dung ham appinitcommom
static
void AppInitCommon(void)
{
	//System Init--------------------------------------------------------------
	SystemCoreClockUpdate();

	//ham timer system tick de xu ly cac su kien thoi gian
	TimerInit();

	//LedControl Init-----------------------------------------------------------------
	LedControl_Init();

	//khoi tao bo dem luu tru danh sach su kien
	EventSchedulerInit(AppStateManager);

	//Cấu hình chân GPIO của các nút nhấn trên mạch.
	EventButton_Init();

	//Cấu hình chân GPIO của còi trên mạch
	BuzzerControl_Init();

	//Cấu hình ngoại vi ADC hoạt động ở chế độ DMA để đọc dữ liệu của cảm biến ánh sáng trên mạch.
	LightSensor_Init(ADC_READ_MODE_DMA);

	//Cấu hình ngoại vi I2C để giao tiếp với cảm biến nhiệt độ - độ ẩm
	TemHumSensor_Init();

	// khoi tao LCD
		Ucglib4WireSWSPI_begin(&ucg, UCG_FONT_MODE_SOLID);
		ucg_ClearScreen(&ucg);

		ucg_SetFont(&ucg, ucg_font_helvR08_tf); // lua chon font chu va co chu
		ucg_SetColor(&ucg, 0, 255, 255, 255); // lua chon mau chu
		ucg_SetColor(&ucg, 1, 0, 0, 0); // lua chon mau background
		ucg_SetRotate180(&ucg); // quay man hinh 180 do

}

int main(void)
{
	AppInitCommon();
	SetStateApp(STATE_APP_STARTUP);
	EventSchedulerAdd(EVENT_APP_INIT);

	while(1){
		processTimerScheduler();
		processEventScheduler();
		//MultiSensorScan();
	};
}
